CAMERA = {
	DEFAULT = {
		PITCH = 5,
		DISTANCE = 600,
		HEIGHT_OFFSET = MAP.HEIGHT_OFFSET,

		MAX_DISTANCE = 1200,
		SPEED_FOR_MIN_DISTANCE = 400,
		SPEED_FOR_MAX_DISTANCE = 1000,
		DISTANCE_CHANGE_TIME = 0.3,
	},
}