PHYSICS = {
	DEFAULT = {	
		MAX_VEL_X = 700,
		ACC_X = 500,
		ACC_X_INTERP = INTERPOLATION.FALL_LINEAR,
	
		MAX_VEL_FALL = 900,
		MAX_VEL_RISE = 700,
		ACC_FALL = 450,
		ACC_RISE = 450,
		ACC_RISE_INTERP = INTERPOLATION.FALL_LINEAR,
	
		ANIM_IDLE = ACT_DOTA_FLAIL,
		ANIM_MOVE = ACT_DOTA_RUN,

		FIXED_Y = MAP.FIXED_Y,
	},
	OLD = {	
		MAX_VEL_X = 700,
		ACC_X = 300,
		ACC_X_INTERP = INTERPOLATION.SIMPLE,
	
		MAX_VEL_FALL = 900,
		MAX_VEL_RISE = 700,
		ACC_FALL = 400,
		ACC_RISE = 300,
		ACC_RISE_INTERP = INTERPOLATION.SIMPLE,
	
		ANIM_IDLE = ACT_DOTA_FLAIL,
		ANIM_MOVE = ACT_DOTA_RUN,

		FIXED_Y = MAP.FIXED_Y,
	},
}