PHYSICS = {
	DEFAULT = {	
		MAX_VEL_X = 750,
		ACC_X = 350,
		ACC_X_INTERP = INTERPOLATION.FALL_LINEAR,
		MIN_VEL_X_INTERP = 200,
	
		MAX_VEL_FALL = 1000,
		MAX_VEL_RISE = 750,
		ACC_FALL = 500,
		ACC_RISE = 350,
		ACC_RISE_INTERP = INTERPOLATION.FALL_LINEAR,
		MIN_VEL_RISE_INTERP = 200,

		HITBOX_RADIUS = 24,

		MASS = 1,
	
		ANIM_IDLE = ACT_DOTA_FLAIL,
		ANIM_MOVE = ACT_DOTA_RUN,

		FIXED_Y = MAP.FIXED_Y,
	},
}