PHYSICS = {
	DEFAULT = {	
		MAX_VEL_X = 750,
		ACC_X = 350,
		ACC_X_INTERP = INTERPOLATION.FALL_LINEAR,
		MIN_VEL_X_INTERP = 200,
	
		MAX_VEL_FALL = 1000,
		MAX_VEL_RISE = 750,
		ACC_FALL = 500,
		ACC_RISE = 350,
		ACC_RISE_INTERP = INTERPOLATION.FALL_LINEAR,
		MIN_VEL_RISE_INTERP = 200,

		HITBOX_RADIUS = 24,
		MASS = 1,
		IMPACT_SPEED = 250,

		WALK_TIME = 3,
		WALK_MAX_SPEED = 200,
		WALK_ACC = 1080,
		WALK_ACC_INTERP = INTERPOLATION.SIMPLE,
		WALK_INTERP_MIN_SPEED = 0,
		JUMP_SPEED = 250,

		FIXED_Y = MAP.FIXED_Y,
	},
}